language: node_js
node_js:
  - "lts/*"
  - "7.6"
services:
  - mongodb
cache:
  directories:
  - node_modules
git:
  depth: 3
before_script:  # https://docs.travis-ci.com/user/database-setup/#MongoDB-does-not-immediately-accept-connections
  - sleep 15
script:
  - yarn test:coverage
after_script:
  - yarn test:report
notifications:
  email: false
